version: '3.8'

services:
  smtp-ctf-lab:
    build:
      context: ../build
      dockerfile: Dockerfile
    container_name: smtp-ctf-lab
    hostname: smtp.ctf.local
    ports:
      - "25:25"
    volumes:
      # Persistance de la mailbox
      - smtp_mailbox:/home/ctf/smtp/mailbox
      # Persistance des logs
      - smtp_logs:/home/ctf/smtp/logs
      # Configuration optionnelle
      - ./config:/home/ctf/smtp/config:ro
    environment:
      # Configuration SMTP
      - SMTP_HOST=0.0.0.0
      - SMTP_PORT=25
      - SMTP_DOMAIN=ctf.local
      - RELAY_DOMAINS=ctf.local,test.com,example.org
      # Limites de sécurité
      - MAX_CONNECTIONS=10
      - MAX_CONNECTIONS_PER_IP=3
      - SESSION_TIMEOUT=300
      - MAX_MESSAGE_SIZE=1048576
      # Mode CTF
      - CTF_MODE=true
      - CTF_LEVEL=intermediate
    networks:
      - smtp-network
    restart: unless-stopped
    # Limites de ressources
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'
    # Santé du conteneur
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "25"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Sécurité
    security_opt:
      - no-new-privileges:true
    read_only: false
    tmpfs:
      - /tmp:noexec,nosuid,size=50m

  # Service optionnel : client de test
  smtp-client-test:
    image: alpine:latest
    container_name: smtp-client-test
    depends_on:
      - smtp-ctf-lab
    networks:
      - smtp-network
    command: |
      sh -c "
        apk add --no-cache telnet netcat-openbsd &&
        echo 'SMTP Test Client Ready!' &&
        echo 'Connect to SMTP server with: telnet smtp-ctf-lab 25' &&
        tail -f /dev/null
      "
    profiles:
      - tools

volumes:
  smtp_mailbox:
    driver: local
  smtp_logs:
    driver: local

networks:
  smtp-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16
    driver_opts:
      com.docker.network.bridge.name: smtp-ctf-br0
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.enable_ip_masquerade: "true"

# Configuration par défaut pour les services
x-default-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3" 