name: Build and Push SMTP Lab Docker Image

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  security-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run security checks
        run: |
          echo "🔍 Running security checks..."
          
          # Check for flag patterns in repository (exclude .github and flag files)
          if grep -r "FLAG{" . --exclude-dir=.git --exclude-dir=.github --exclude=flag.txt --exclude=flag_inject.example; then
            echo "❌ FLAG{ patterns found in repository!"
            exit 1
          fi
          
          # Check if flag.txt is committed
          if git ls-files | grep -q "^flag\.txt$"; then
            echo "❌ flag.txt should not be committed!"
            exit 1
          fi
          
          # Check if flag example exists
          if [ ! -f "flag_inject.example" ]; then
            echo "❌ flag_inject.example missing!"
            exit 1
          fi
          
          echo "✅ Security checks passed!"

  build-and-push:
    runs-on: ubuntu-latest
    needs: security-check
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Create flag file for build
        run: |
          echo "FLAG{SMTP_RELAY_MISCONFIGURATION_EXPLOITED}" > flag.txt
          cp flag.txt deploy/

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./build
          file: ./build/Dockerfile
          push: true
          tags: |
            cyberctf/smtp-relay-vuln-lab:latest
            cyberctf/smtp-relay-vuln-lab:${{ github.sha }}
          secrets: |
            "flag=flag.txt"
          platforms: linux/amd64,linux/arm64

      - name: Cleanup flag file
        run: |
          rm -f flag.txt
          rm -f deploy/flag.txt

  test-lab:
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create flag file for testing
        run: |
          echo "FLAG{SMTP_RELAY_MISCONFIGURATION_EXPLOITED}" > flag.txt
          cp flag.txt deploy/

      - name: Start SMTP lab
        run: |
          cd deploy
          DOCKER_BUILDKIT=1 docker-compose up -d --build
          sleep 30

      - name: Test SMTP connectivity
        run: |
          # Wait for service to be ready
          timeout 60 bash -c 'until echo "QUIT" | nc localhost 25; do sleep 2; done'

      - name: Run vulnerability tests
        run: |
          # Test user enumeration
          echo -e "VRFY ceo\r\nQUIT" | nc localhost 25 | grep -q "250 ceo@acmelogistics.local"
          
          # Test normal relay (should fail)
          echo -e "HELO attacker.com\r\nMAIL FROM: <attacker@evil.com>\r\nRCPT TO: <victim@external.com>\r\nQUIT" | nc localhost 25 | grep -q "554 Relay access denied"
          
          # Test vulnerability (should succeed)
          echo -e "HELO attacker.com\r\nMAIL FROM: <ceo@acmelogistics.local>\r\nRCPT TO: <attacker@external.com>\r\nQUIT" | nc localhost 25 | grep -q "250 Ok"

      - name: Run auto-solve script
        run: |
          python3 test/auto_solve.py

      - name: Cleanup
        run: |
          cd deploy
          docker-compose down
          rm -f flag.txt
          rm -f deploy/flag.txt

  documentation:
    runs-on: ubuntu-latest
    needs: security-check
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate README
        run: |
          # Check if README contains required sections
          grep -q "Acme Logistics SMTP Relay Vulnerability Lab" README.md
          grep -q "FLAG{SMTP_RELAY_MISCONFIGURATION_EXPLOITED}" README.md
          grep -q "DOCKER_BUILDKIT" README.md

      - name: Check lab structure
        run: |
          # Verify required files exist
          [ -f "build/smtp_server.py" ]
          [ -f "build/Dockerfile" ]
          [ -f "deploy/docker-compose.yml" ]
          [ -f "test/auto_solve.py" ]
          [ -f "test/check_smtp.sh" ]
          [ -f "flag_inject.example" ]
          [ -f ".gitignore" ]

      - name: Verify no CTF terminology in business context
        run: |
          # Check that business language is used instead of CTF terms
          if grep -r "challenge\|flag\|score\|hack\|exploit" README.md --ignore-case | grep -v "FLAG{SMTP_RELAY_MISCONFIGURATION_EXPLOITED}"; then
            echo "❌ CTF terminology found in business context!"
            exit 1
          fi 